Add uninstall function; add uninstall to work installer files

diff --git a/install-generic b/install-generic
--- a/install-generic
+++ b/install-generic
@@ -11,3 +11,7 @@ if [[ -z $DOTFILES ]]; then
 fi
 
 stow_install $DOTFILES ~/ $STOW_FOLDERS
+if [[ $? -ne 0 ]]; then
+  echo "Installation failed."
+  exit 1
+fi
diff --git a/install-work b/install-work
--- a/install-work
+++ b/install-work
@@ -1,15 +1,39 @@
 #!/usr/bin/env zsh
 SCRIPT_DIR="$( cd "$( dirname "${(%):-%x}" )" &> /dev/null && pwd )"
 source $SCRIPT_DIR/utils/install-helpers.sh
+stow_action=stow_install
+
+while getopts "hD" opt; do
+  case $opt in
+    h)
+      echo "Usage: install-work [-h] [-D]"
+      echo "-h shows this"
+      echo "-D uninstalls"
+      exit 0
+      ;;
+    D)
+      read "reply?Are you sure you want to uninstall $selected? (y/N) "
+      echo 
+      if [[ ! $reply =~ ^[Yy]$ ]]; then
+        echo "Aborting"
+        exit 0
+      fi
+      stow_action=stow_uninstall
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
 
 if [[ -z $STOW_FOLDERS ]]; then
-  STOW_FOLDERS="bin,nvim,tmux,zsh"
+  STOW_FOLDERS="bin,nvim,oh-my-zsh,tmux,zsh"
 fi
 
 if [[ -z $DOTFILES ]]; then
   DOTFILES=$HOME/.dotfiles
 fi
-
 selected=$(find $DOTFILES/work/* -type d -o -type l -maxdepth 0 | fzf )
 if [[ -z $selected ]]; then
   echo "Must select a work dir to install"
@@ -18,6 +42,19 @@ fi
 selected_name="$(basename "$selected" | tr . _)"
 
 # Install generic, universal packages
-stow_install $DOTFILES ~/ $STOW_FOLDERS
+# If these folders don't exist, they will eventually be created and end up in dotfiles.
+# Alternatively, I coul add something in to selectively `--no-folding` the bin directory, 
+# but it was easier to do this for now
+mkdir -p ~/.local/share ~/.local/state 
+$stow_action $DOTFILES ~/ $STOW_FOLDERS
+if [[ $? -ne 0 ]]; then
+  echo "Installation of generic packages failed."
+  exit 1
+fi
+
 # Install machine-specific work packages
-stow_install $DOTFILES/work ~/ $selected_name
+$stow_action $DOTFILES/work ~/ $selected_name
+if [[ $? -ne 0 ]]; then
+  echo "Installation of work-specific packages failed."
+  exit 1
+fi
